# Generated by Django 4.0.1 on 2022-01-12 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_1', models.CharField(choices=[('na', '해당없음'), ('epic', '에픽'), ('unique', '유니크'), ('legendary', '레전드리')], max_length=9)),
                ('ability_2', models.CharField(choices=[('na', '해당없음'), ('epic', '에픽'), ('unique', '유니크'), ('legendary', '레전드리')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Star_Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_force', models.CharField(choices=[('na', '해당없음'), ('under_17', '17성 이하'), ('up_17', '17성 초과')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='DealItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('server', models.CharField(max_length=20, verbose_name='서버')),
                ('group', models.CharField(max_length=20, verbose_name='직업군')),
                ('part', models.CharField(max_length=20, verbose_name='부위')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('price_kind', models.BooleanField(default=True, verbose_name='억/엄')),
                ('content', models.TextField()),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
