# Generated by Django 4.0.1 on 2022-01-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('방어구', '방어구'), ('장신구', '장신구'), ('무기', '무기'), ('캐시', '캐시'), ('교불', '교불')], max_length=10, verbose_name='종류')),
                ('part_armor', models.CharField(choices=[('모자', '모자'), ('상의', '상의'), ('하의', '하의'), ('한벌옷', '한벌옷'), ('장갑', '장갑'), ('망토', '망토'), ('신발', '신발')], max_length=10, null=True, verbose_name='부위_방어구')),
                ('part_accessory', models.CharField(choices=[('얼굴장식', '얼굴장식'), ('눈장식', '눈장식'), ('귀고리', '귀고리'), ('어깨장식', '어깨장식'), ('반지', '반지'), ('펜던트', '펜던트'), ('벨트', '벨트'), ('포켓아이템', '포켓아이템')], max_length=10, null=True, verbose_name='부위_장신구')),
                ('part_weapon', models.CharField(choices=[('주무기', '주무기'), ('보조무기', '보조무기')], max_length=10, null=True, verbose_name='부위_무기')),
                ('star_force', models.CharField(choices=[('해당없음', '해당없음'), ('17성 이하', '17성 이하'), ('17성 초과', '17성 초과')], max_length=9, null=True, verbose_name='스타포스')),
                ('ability_1', models.CharField(choices=[('해당없음', '해당없음'), ('에픽', '에픽'), ('유니크', '유니크'), ('레전드리', '레전드리')], max_length=9, null=True, verbose_name='윗잠')),
                ('ability_2', models.CharField(choices=[('해당없음', '해당없음'), ('에픽', '에픽'), ('유니크', '유니크'), ('레전드리', '레전드리')], max_length=9, null=True, verbose_name='아랫잠')),
            ],
        ),
        migrations.CreateModel(
            name='DealItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('server', models.CharField(max_length=10, verbose_name='서버')),
                ('category', models.BooleanField(default=True, verbose_name='장비/기타')),
                ('group', models.CharField(max_length=10, verbose_name='직업군')),
                ('kind', models.CharField(max_length=10, verbose_name='종류')),
                ('part', models.CharField(max_length=10, verbose_name='부위')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('price_kind', models.BooleanField(default=True, verbose_name='억/엄')),
                ('star_force', models.CharField(max_length=9, null=True, verbose_name='스타포스')),
                ('ability_1', models.CharField(max_length=9, null=True, verbose_name='윗잠')),
                ('ability_2', models.CharField(max_length=9, null=True, verbose_name='아랫잠')),
                ('content', models.TextField()),
                ('sale_buy', models.BooleanField(default=True, verbose_name='삼/팜')),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
