# Generated by Django 4.0.1 on 2022-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealitems',
            name='group',
            field=models.CharField(choices=[('warrior', '전사'), ('magician', '마법사'), ('archer', '궁수'), ('thief', '도적'), ('pirate', '해적')], max_length=10, verbose_name='직업군'),
        ),
        migrations.AlterField(
            model_name='dealitems',
            name='part',
            field=models.CharField(choices=[('cap', '모자'), ('top', '상의'), ('bottom', '하의'), ('dress', '한벌옷'), ('gloves', '장갑'), ('cape', '망토'), ('shoes', '신발')], max_length=10, verbose_name='부위'),
        ),
    ]
