# Generated by Django 4.0.1 on 2022-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('server', models.CharField(choices=[('베라', '베라'), ('스카니아', '스카니아'), ('루나', '루나'), ('제니스', '제니스'), ('크로아', '크로아'), ('유니온', '유니온'), ('엘리시움', '엘리시움'), ('이노시스', '이노시스'), ('레드', '레드'), ('오로라', '오로라'), ('아케인', '아케인'), ('노바', '노바')], max_length=9)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
