# Generated by Django 4.0.1 on 2022-01-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('server', models.CharField(choices=[('scania', '스카니아'), ('bera', '베라'), ('luna', '루나'), ('zenith', '제니스'), ('croa', '크로아'), ('union', '유니온'), ('elysium', '엘리시움'), ('enosis', '이노시스'), ('red', '레드'), ('aurora', '오로라'), ('arcane', '아케인'), ('nova', '노바')], max_length=9)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
