# Generated by Django 4.0.1 on 2022-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ct_id',
            field=models.PositiveIntegerField(default=14, verbose_name='content_type_id'),
        ),
    ]
