# Generated by Django 4.0.1 on 2022-03-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_like',
            name='ct_id',
            field=models.PositiveIntegerField(default=12, verbose_name='content_type_id'),
        ),
        migrations.AlterField(
            model_name='photo_post',
            name='ct_id',
            field=models.PositiveIntegerField(default=11, verbose_name='content_type_id'),
        ),
    ]
