# Generated by Django 4.0.1 on 2022-02-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_post',
            name='ct_id',
            field=models.PositiveIntegerField(default=10, verbose_name='content_type_id'),
        ),
    ]
