# Generated by Django 4.0.1 on 2022-02-24 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0002_photo_post_ct_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(upload_to='photo')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('ct_id', models.PositiveIntegerField(default=10, verbose_name='content_type_id')),
                ('likes_user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo_post')),
            ],
        ),
    ]
