# Generated by Django 4.0.1 on 2022-02-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noti_item',
            name='noti_id',
        ),
        migrations.AddField(
            model_name='noti_item',
            name='noti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noti.noti'),
        ),
    ]
