# Generated by Django 4.0.1 on 2022-02-18 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('noti', '0002_remove_noti_item_noti_id_noti_item_noti'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='noti_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='noti_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
