# Generated by Django 4.0.1 on 2022-02-21 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noti', '0003_noti_noti_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성날짜'),
            preserve_default=False,
        ),
    ]
