# Generated by Django 4.0.1 on 2022-01-25 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='제목')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='갱신날짜')),
                ('server', models.CharField(max_length=10, verbose_name='서버')),
                ('boss', models.CharField(max_length=20, verbose_name='보스')),
                ('level', models.CharField(max_length=10, verbose_name='난이도')),
                ('total', models.PositiveIntegerField(verbose_name='인원')),
                ('job', models.CharField(blank=True, max_length=10, null=True, verbose_name='직업')),
                ('content', models.TextField()),
                ('kind', models.BooleanField(default=True, verbose_name='구인/구직')),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
