# Generated by Django 4.0.1 on 2022-01-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='price',
        ),
    ]
