# Generated by Django 4.0.1 on 2022-01-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_post_job_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_job',
            name='job',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='직업'),
        ),
    ]
